name: Build MLC LLM iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build archive
        run: |
          cd ios
          xcodebuild -scheme MLCChat \
          -configuration Release \
          -sdk iphoneos \
          -archivePath ../build/App.xcarchive archive

      - name: Export unsigned IPA
        run: |
          cd build
          mkdir Payload
          cp -R App.xcarchive/Products/Applications/*.app Payload/
          zip -r app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/app.ipa